server:
  port: 8083

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    # 开启Mysql的外键支持
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/Food
    username: temp
    password: 123456
logging:
  level:
    top.dccif.foodservice: debug

